#define		ActionNum_5_len 	5 
#define		Action_10_len 		10 
#define		Action_1_len 		1 
#define		Action_9_len 		9 
#define		AuthQuarter_len 	5 
#define		AuthType_len 		5 
#define		Cancled_5_len 		5 
#define		CharNew7_len 		7
#define		CharNew_len 		2
#define		City_20_len 		20
#define		ContractType_2_len 	2	
#define		ContractType_5_len 	5	
#define		CrType_5_len 		5 
#define		DateYYMMDD_6_len 	6 
#define		DateYYMM_4_len 		4 
#define		DateYYMM_5_len 		5
#define		DateYYYYMMDD_len 	8
#define		Days_len 		5
#define		Douse_len 		5
#define		Elegebility_5_len 	5 
#define		Elegebility_6_len 	6
#define		Employee_len 		5
#define		Error_len 		5 
#define		FirstName_8_len 	8
#define		IdCode_1_len 		1 
#define		IdCode_2_len 		2 
#define		IdCode_5_len 		5
#define		IdNumber_10_len 	10	
#define		IdNumber_9_len 		9	
#define		LabId_3_len 		3 
#define		LastName_14_len 	14
#define		Limit_10_len 		10 
#define		LineIndex_2_len 	2 
#define		LocationId_10_len 	10
#define		LocationId_7_len 	7 
#define		LocationId_9_len 	9 
#define		MedicineCode_len 	9
#define		NoteType_2_len 		2 
#define		Note_30_len 		30 
#define		NumberOfPacages_len 	5
#define		ObservationCode_len 	10
#define		PayingInst_len 		6
#define		PaymentType_len 	2	
#define		Phone_10_len 		10
#define		Position_len 		2	
#define		Prescriptions_len 	9
#define		Profession_len 		5
#define		Quantity_len 		5
#define		ReqCode_5_len 		5 
#define		ReqId_9_len 		9 
#define		Result_10_len 		10 
#define		Route_9_len 		9 
#define		ShiftStatus_len 	5 
#define		Street_16_len 		16
#define		TaxAm_5_len 		5 
#define		TaxAmount_5_len 	5	
#define		TermId_10_len 		10
#define		TermId_7_len 		7 
#define		Location_7_len 		7  //31102000
#define		TermId_9_len 		9 
#define		TimeHHMMSS_len 		6
#define		TimeHHMM_4_len 		4
#define		TimeHHMM_5_len 		5
#define		TreatmentContr_len 	9
#define		Units_15_len 		15 
#define 	TMaccabiMagenCode_len  	3
#define 	TMemberRightsCode_len	3
#define 	TPermissionType_len	2
#define 	Tdiary_month_len	4
#define 	Tmac_magen_code_len	TMaccabiMagenCode_len
#define 	Tmaccabi_code_len	TMemberRightsCode_len	
#define		Mahoz_len			2         //  GAL  13/01/2003
